wrapper:
  config_file_name: mid360.yaml
  lidar_topic: /livox/lidar
  imu_topic: /livox/imu
  lidar_type: 0 # 0)avia
  blind: 0.5
  det_range: 100.0

front_end:
  extrin_r: [1,0,0,
            0,1,0,
            0,0,1]
  extrin_t: [-0.011,-0.02329,0.04412  ]
  enable_record: false
  record_file_name: record.txt
  gravity_align: false
  filter_leaf_size: 0.2
  extrinsic_est_en: false

ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001