wrapper:
  config_file_name: velodyne.yaml
  lidar_topic: /velodyne_points
  imu_topic: /handsfree/imu
  lidar_type: 1 # 0)avia 1) velodyne
  blind: 0.5

front_end:
  extrin_r: [1,0,0,
            0,1,0,
            0,0,1]
  extrin_t: [-0.27255, 0.00053,-0.17954]
  enable_record: false
  record_file_name: record.txt
  gravity_align: false
  filter_leaf_size: 0.2
  extrinsic_est_en: false
ieskf:
  cov_gyroscope: 0.1
  cov_acceleration: 0.1
  cov_bias_acceleration: 0.0001
  cov_bias_gyroscope: 0.0001